# Generated by Django 3.2.13 on 2022-06-16 01:38

import csv
import sys
from django.db import migrations

def import_data(apps, scheme_editor):
    Flight = apps.get_model('flights', 'Flight')
    with open('../data/flights.csv') as f:
        reader = csv.reader(f)
        next(reader, None) # skip the headers
        for row in reader:
            Flight.objects.get_or_create(
                id=row[0],
                created_at=row[1],
                updated_at=row[2],
                flight_identifier=row[3],
                flt_num=row[4],
                scheduled_origin_gate=row[5],
                scheduled_destination_gate=row[6],
                out_gmt=row[7],
                in_gmt=row[8],
                off_gmt=row[9],
                on_gmt=row[10],
                destination=row[11],
                origin=row[12],
                destination_full_name=row[13],
                origin_full_name=row[14]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_create_flight_model'),
    ]

    operations = [
        migrations.RunPython(import_data)
    ] if "test" not in sys.argv else []
