# Generated by Django 3.2.13 on 2022-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_import_flight_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination_full_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_full_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Origin'),
        ),
    ]
